### ISSUE TITLE
dublicatewdx.lua: Подсчёт контрольных сумм

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#1]
Может быть есть смысл заменить ```md5sum``` на ```sha1sum```? Немного подольше, зато вероятность коллизий ниже.

P.S. С RHash не сравнивал, не уловил, как засечь время.

**Comment by j2969719** [comment]
хз нафиг я эту хрень вообще в живых оставил. простая кнопка с баш-скриптом куда быстрее и надежнее.
эту хрень при следующем поиске вообще надо запускать с перезаписью и останавливать + не факт что dc всегда обходит файлы с самого верхнего каталога...

p.s. выложи куда свои плагины, а то ссылка на транслит опять мертвая
