### ISSUE TITLE
gtkimgview: Add TIFF

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#10]
Предлагаю добавить в дефолтную детект-строку gtkimgview расширения TIFF (```TIF```/```TIFF```), работает и, вроде, пошустрее встроенного (особенно покрупнее, под рукой были до 80ти Мб).

Проблем с ходовыми алгоритмами сжатия не заметил (проверял многослойные, экспортнул: без сжатия, LZW, Pack Bits, Deflate, JPEG).

**Comment by j2969719** [comment]
ок, сам не проверял т.к. у мну на него костыль на atril повешен, да и под рукой кроме одной книги ничего нет

**Comment by Skif-off** [comment]
Тут внезапно вспомнил: не проверял многостраничные TIFF, не попадались (во встроенном просмотрщике тоже). Atril умеет?

Примеры можно попробовать [нагуглить](https://www.google.com/search?q=multi+page+tiff+example).

**Comment by j2969719** [comment]
да, книга как раз многостраничными тифами, но 1.16 походу открывает иногда с косяками. [отсюда](http://www.nightprogrammer.org/development/multipage-tiff-example-download-test-image-file/) второй не открывается ни костылем, ни самой прогой(крайний evince открывает), а вот gtkimgview первую страницу таки рисует

**Comment by j2969719** [comment]
сейчас детектстрока по идее будет формироваться из всех поддерживаемых форматов которые теоретически можно открыть. гарантий нет, но хотя бы попытается и пошлет дальше по списку если не.

**Comment by Skif-off** [comment]
С многостраничными вроде Evince (который "Просмотр документов") вроде справляется... Осталось понять, когда его потребуется запустить :)) Радует, что попадаются не часто.

> сейчас детектстрока по идее будет формироваться из всех поддерживаемых форматов которые теоретически можно открыть.

Штука полезная, один момент не уловил: список расширений, указанный в настройках DC, будет игнорироваться и плагин "сам решит"?

**Comment by j2969719** [comment]
не, в смысле если в настройках удалить и подключить плагин заново должна прописаться детект-строка со всеми форматами
по списку расширений в настройках DC решает пускать ли плагин для переданного на просмотр файла. его нельзя игнорировать, но можно например просто прописать `EXT="*"` какой. хотя хз как тогда оно поведет с гигобайтными файлами или какими из /dev и т.п.

**Comment by j2969719** [comment]
> Осталось понять, когда его потребуется запустить

хреново что `libmagic` не определяет число страниц.. имхо самый ненапряжный вариант - это просто накидать какой луа-скрипт на `identify` и повесить на подсказку для tiff и т.п.

**Comment by Skif-off** [comment]
Понял, спасибо.

Насчёт ```identify ```: чё-т даже не подумал поискать :) Вчера на телефоне начал набрасывать вариант чисто на Lua (читать первые байты и попробовать разобраться), практически пока не щупал.
