### ISSUE TITLE
wlxPView (aka dcpoppler): Глюк панели при переходе к следующему/предыдущему файлу

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#11]
В общем, сабж. Переходить нужно или горячими клавишами, или через пункты в меню Файл, туда-обратно. Выглядит это как-то вот так:

![1](https://user-images.githubusercontent.com/6333198/36807276-6ba36160-1cba-11e8-80f1-98419f7bdeea.png)

К слову, было бы здорово к кнопке "First page" добавить и "Last page". Тут листал 69 страниц, но почему-то только к 42й в голову пришла такая мысль :))

**Comment by j2969719** [comment]
про не убиваемые плагины(с просмотром картинок будет так же походу т.к. с лэйблом на тулбаре оно очень заметно) писал на форуме у себя сделал так:
```
Index: doublecmd/src/fviewer.pas
===================================================================
--- doublecmd/src/fviewer.pas	(revision 7994)
+++ doublecmd/src/fviewer.pas	(working copy)
@@ -2254,6 +2254,7 @@
 
 procedure TfrmViewer.cm_Reload(const Params: array of string);
 begin
+  ExitPluginMode;
   LoadFile(iActiveFile);
 end;
 
@@ -2298,6 +2299,7 @@
       Exit;
 
   end;
+  ExitPluginMode;
   if pnlPreview.Visible then
     begin
       if DrawPreview.Col = 0  then
@@ -2680,6 +2682,7 @@
 
 procedure TfrmViewer.cm_ShowPlugins(const Params: array of string);
 begin
+  ExitPluginMode;
   bPlugin:= CheckPlugins(FileList.Strings[iActiveFile], True);
   if bPlugin then
   begin

```
кнопку добавил

**Comment by Skif-off** [comment]
Спасибо за кнопку!

> писал на форуме

Ага, припоминаю смутно, думал уточнить, что там и как. но SF.net опять в дауне... Занятно, ```ExitPluginMode``` есть в функции загрузки следущего файла, но отсутствует в функции загрузки предыдущего (для которой ```@@ -2298,6 +2299,7 @@```) - непонятное решение, как-то нелогично.

> с просмотром картинок будет также походу

Не сталкивался, только с этим плагом вылезло внезапно. А в быстром просмотре почему-то работает без проблем вроде.

**Comment by Skif-off** [comment]
Пожалуй, надо будет снова поднять вопрос на форуме, как оживёт? Пакость неприятная, ибо блокирует элементы управления (спасибо за хоткеи, стеснялся спросить, возможно ли :))

**Comment by j2969719** [comment]
если будет время, глянь работает счас оно у тебя с крайним говнокостылем на масштабирование

**Comment by Skif-off** [comment]
Собрал, глюк на месте.

Счётчик страниц работает не очень хорошо:
- нажатие клавиш 1-7 получает сам просмотрщик, переключая вид;
- не работает клавиша Enter на цифровом блоке клавиатуры, только каноничный.

**Comment by Skif-off** [comment]
> так понял страница видна?

Не понял, какая страница видна? Ты про масштабирование? Вроде работает, алгоритм расчёта не уловил, но вид по умолчанию вроде нормальный (только на больших мониторах в большом размере нет возможности проверить), галочка работает, проверил на нескольких файлах - чисто текстовых и только из картинок, без текстового слоя.

> так понял страница видна?

Скролл - это тоже годно, совместить гемор?

>с глюком или патчить вьювер или переносить все кроме кновок с тулбрара

Не понял, что и куда переносить, соображаю сегодня медленно :) Но глюк давай пока оставим, оффорум оживёт - призовём, так сказать, **Alexx2000**. (Заодно прицепом надо будет попросить посмотреть переключение вида цифрами при быстром просмотре, как-то он странно работает.)

> mpv и остальное через сокет тоже не убивается?

В смысле "не убивается"? Вроде всё как обычно.

**Comment by j2969719** [comment]
можешь вернуть 
`g_signal_connect(G_OBJECT(spinbtn), "value-changed", G_CALLBACK(tb_spin_changed), (gpointer)canvas);`
в ListLoad. мне не нравится его поведение с костылем на фокус.

с mpv как и wlxmplayer по идее будет стоять какофония из всех запущенных плееров если тоже как тут понажимать предыдущий и т.п.

**Comment by Skif-off** [comment]
> можешь вернуть

Не-не-не, и так вношу некоторые правки, не хочу ещё больше отслеживать :)

> по идее будет стоять какофония из всех запущенных плееров

Не сталкивался, чаще отдельно запускаю (вдруг DC рухнет или ешё чего?), [такой скрипт](https://github.com/jonniek/mpv-filenavigator) ещё прикрутил. Тут вроде фикс небольшой, можно подождать, оживёт же SF.net рано или скоро ([видел](https://github.com/doublecmd/doublecmd), кстати? Вики уже вроде целиком перенесена).

К слову, может, есть смысл поменять расположение элементов, чуток пологичнее?
> First page
> Previous page
> Next page
> Last page
> Current page

**Comment by j2969719** [comment]
поменял 
ну, ковырять я его вряд ли особо буду т.к. и так уже натворил какой-то макаронный ад, что слабонервным лучше не видеть.. не падает от двух открытых вьюверов и черт с ним.
там на вики пару страниц обновить стоит(типа qt5 в supported platforms или тему для мака https://github.com/topics/double-commander в alternative graphics и т.п.)

**Comment by j2969719** [comment]
https://sourceforge.net/p/doublecmd/code/8013/
по идее счас не должно, но надо смотреть как с плагинами от tc оно счас
закрываю
