### ISSUE TITLE
[Lua-wdx] io.open/io.popen mode

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#12]
Касательно коммита [220](https://github.com/j2969719/doublecmd-plugins/commit/b1671de76b9bd2903aa7c89829d6600384e3988a), добавление режима "r": а его нужно специально добавлять? По умолчанию в ```io.open``` и ```io.popen``` вроде как как раз "r" и используется?
(У себя вроде только в последнем "Search by dependencies in ELF" нашёл - копипаста из ```fulltextodtwdx.lua```, кажется, лень было всё с нуля писать).

P.S. А что значит "kek"? :) "КЕМ" знаю, а тут теряюсь в догадках :))

Edit: Глянул в [документации](https://www.lua.org/manual/5.1/manual.html#pdf-io.open), по идее - не нужно. Или что-то упускаю?

**Comment by j2969719** [comment]
не, не нужно, я потом тоже [почитал](https://doublecmd.sourceforge.io/forum/viewtopic.php?f=8&t=806&start=60) 
с луа просто давно не игрался, тогда проверил твой скрипт и dc не повис..
