### ISSUE TITLE
mpv (wlx): Параметры запуска

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#13]
Может быть, есть смысл вынести параметры запуска в ini-файл?

**Comment by j2969719** [comment]
нуок, накастылял, но опять не тестил особо так что как обычно..
по идее счас можно менять детектстроку без рекомпила, но нужно заново переподключать так что особого толку с этого нет
прописывать абсолютный путь к mpv
прописывать отдельные параметры для аудио и видео 
прописывать отдельные параметры для определенного типа(как детектит файл можешь глянуть в выхлопе, строка content_type = xxxxx/xxxx )

**Comment by Skif-off** [comment]
Спасибо, много получилось :) Правда, с дополнительными фичами пока не разобрался.

**Comment by j2969719** [comment]
костылял ради количества хз насколько оно вообще нужно. отдельный конфиг ради одной строчки чет не ахти, а в общий конфиг для wlx я своими кривыми руками лезть стремаюсь. 
счас тупо можно cmd(путь к mpv) и params(все параметры кроме id окна и имени файла) в разных секциях переопределять.  приоритет секций: расширение>mime>аудио или видео>дефолт
