### ISSUE TITLE
mpv (wlx): Сломался просмотр при переходе к следующему/предыдущему

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#14]
После [этого коммита](https://github.com/j2969719/doublecmd-plugins/commit/384703bc5e44f47e74814911fffcd9607a539163#diff-5b7be68c0c9ef5501742778de7a35a7c) переход к следующему/предыдущему файлу не гасит запущенную(ые) копии mpv (и быстрый, и обычный просмотр).

**Comment by j2969719** [comment]
йэп, и подходящих сигналов на переключение не знаю, надо откатывать..
