### ISSUE TITLE
Lua: Зачем лишняя проверка SysUtils.DirectoryExists()?

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#15]
В крайних коммитах добавлено
```lua
if (SysUtils.DirectoryExists(FileName)) then 
   return nil; 
end
```
а зачем? Там далее идёт
```lua
local attr = SysUtils.FileGetAttr(FileName);
```
можно и на другой атрибут здесь же проверить:
```lua
if (math.floor(attr / 0x00000010) % 2 ~= 0) then
  return nil; 
end
```
или объединить в одно условие с оператором ```or```.

По идее, один запрос к файловой системе и два сравнения быстрее двух запросов (одного и того же, кажется) и двух сравнений?

**Comment by j2969719** [comment]
> а зачем?

https://www.youtube.com/watch?v=F2skk6RFFos
а если серьезно, в моем отстойнике копипаста просто туда-сюда качует.
там и саму проверку аттрибутов можно счас вырубить, хотя в тех конкретных случаях оно без надобности. говнокод есть говнокод. поменял

**Comment by Skif-off** [comment]
Если серьёзно, то если не все так делают, то многие :) Сам вроде вообще ни одного с нуля не сделал: сначала копипаста с одного из изкоробочных (когда их ещё два было, ```simplewdx.lua```, кажется), потом - какой первый под курсор упадёт.
