### ISSUE TITLE
emblems.wdx: Вывод информации

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#16]
Может быть, есть смысл попробовать выпилить из строки ```emblem-``` и квадратные скобки? Если не влом и не скажется на производительности :)
Вывод ведь не дистрибутиво-зависимый?

**Comment by j2969719** [comment]
влом если чеснок
от тем иконок походу зависит, кавычки из-за того что оригинал скорее массив строк
мудохатся со строками в си(особенно если его еще и не знаешь) то еще удовольствие + учитывая что не все они начинаются с `emblem-` + через emblemize какой можно вообще любую иконку насадить. 

проще и быстрее на луа через gio info (или gvfs-info) делать ` gio info -a metadata::emblems /путь`

**Comment by j2969719** [comment]
накостылял конфиг в котором можно задавать соответствия

**Comment by j2969719** [comment]
скорее на стабильности скажется -  где-то налажал с памятью и мозга не хватает понять где, мож еще после работы поковыряю

счас эмблемы берутся не строкой а массивом, который по очереди обходится и по колхозному склеивается(в format можно поменять как склеивать будет) в возвращаемую строку. если допустим элемент массива типа например `emblem-downloads` есть в конфиге, то вместо его вклеивается значение оттуда. всякие `emblem-documents-symbolic` или `emblem-documents-symbolic.symbolic` надо тоже самому добавлять отдельно

**Comment by Skif-off** [comment]
А если у нас ```emblem-downloads-gray```, а в конфиге только ```emblem-downloads```, то что будет? Проигнорирует или вклеит?

**Comment by j2969719** [comment]
просто проигнорит и вклеит `emblem-downloads-gray` без изменений, в конфиге ищет значение замены именно для `emblem-downloads-gray` 
чтоб подменял надо добавлять и `emblem-downloads` и `emblem-downloads-gray` и т.п.
