### ISSUE TITLE
gtk_socket.wlx: CSV-Viewer: Дополнение расширением TSV

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#17]
По сути этот вьювер для DSV вообще, сначала подумал - только CSV-файлы, с запятой, хотя на русском чаще с точкой с запятой ";", а [тут](https://github.com/j2969719/doublecmd-plugins/blob/master/plugins/wlx/gtk_socket/csv-viewer/csv-viewer-plug-gtk2#L108) разглядел:
```python
        dialect = sniffer.sniff(sample)
        reader = csv.reader(f, dialect)
```
и посмотрел этот Sniffer в модуле ```csv``` - там и запятая, и табуляция, и точка с запятой, и пробел, и ещё ", ".
Тогда, может быть, стоит сразу дополнить ```settings.ini```, чтобы было понятнее?
```diff
 # [csv]
 # GTK2
 # command = /path/to/csv-viewer-plug-gtk2 -w %d %s
 # GTK3
 # command = /path/to/csv-viewer-plug -w %d %s
+# [tsv]
+# redirect = csv
```

P.S. Есть репорты от других пользователей? Тут - полтора десятка и только от меня, как-то неловко стало :)

**Comment by j2969719** [comment]
ок, добавил
этим говном кроме мну вряд ли кто вообще пользуется, кому тут репортить хоспади)
закрываю
