### ISSUE TITLE
gotolinkpath.lua: Добавить для readlink ключ -m или -f

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#18]
... и получить канонический путь. ```-m``` безопаснее, т.к. не требует существование каждого элемента в пути.

**Comment by j2969719** [comment]
ок, чет накостылял но не тестил

**Comment by Skif-off** [comment]
С последним коммитом та же фигня, в условии срабатывает
```lua
(SysUtils.DirectoryExists(path) == false)
```
из-за ```\n```. А если так убрать:
```lua
path = string.match(output, "(.*)[\n]");
```
? Или ```string.gsub()``` натравить?

**Comment by Skif-off** [comment]
Может быть, стоит добавить ```-n``` и в ```editsymlink.lua```?
К слову, у него стоит проверять значение (длину, например) т.к. срабатывает и на самых обычных файлах и папках, не только на симлинках.

**Comment by j2969719** [comment]
да, косяк, счас не должно по идее
я на эти говноскрипты забил примерно сразу как накостылял т.к. толку от них на деле ноль

**Comment by j2969719** [comment]
счас еще заметил что у диалогов dc походу есть лимит на строку так что весь путь может тупо не влезть
эту хрень походу вообще опасно юзать так что лучше снесу ее

**Comment by j2969719** [comment]
> Мне кажется, только не хватает предупреждения, что файл/папка будут удалены (имею в виду параметр -n), и непонятно, почему условие такое

>if (SysUtils.DirectoryExists(newpath)) then
если это может быть и файл. SysUtils.FileGetAttr()?

походу я чет туплю но -n вроде ж должен делать однозначную ссылку на папку, поэтому и проверку такой делалO_o

прост в посте на форуме была utils да и костыль на суши хотел из скриптов выкинуть

**Comment by j2969719** [comment]
а про предупрежение, его просто для перезаписи симлинка добавить?

**Comment by Skif-off** [comment]
Наверное, всё-таки не нужно, мы ведь её редактируем и без ```-f``` тут не обойтись?

**Comment by j2969719** [comment]
хз есличеснок, если так как счас сделано, то без него ln просто ругаться что симлинк уже есть
