### ISSUE TITLE
FreeArch

### ISSUE THREAD

**Issue by modz2014** [j2969719/doublecmd-plugins#23]
hey mate i cant open a issue on your FreeArch its archived i was wondering if you would add the compression ratio to 7zip i cant seem to find it and add it myself the compression raito is bigger then 7zip i can compress 30gb down to 15gb 7zip compresses it down to 23gb there is a big difference can you add it please

**Comment by j2969719** [comment]
actual freearc developer - [Bulat Ziganshin](https://github.com/Bulat-Ziganshin)

i just saved some old sources from the now defunct freearc.org for personal needs.
i do not plan to make changes to the existing code base, therefore the repository is archived
