### ISSUE TITLE
How To Install it?! (Windows 10)

### ISSUE THREAD

**Issue by ThEnchanted** [j2969719/doublecmd-plugins#24]
Hello, I can't understand what settings I need to change to make from the bright white to the dark theme...
P.s I'm using the portable version

**Comment by j2969719** [comment]
i dont use windows so i have no idea. this repo contains mainly some crappy linux plugins and cross platform scripts. the only thing that can somehow be related to dark themes is a couple of modified  highlight files for the internal editor [here](https://github.com/j2969719/doublecmd-plugins/tree/master/dark-theme).
