### ISSUE TITLE
Read office file app and version

### ISSUE THREAD

**Issue by gitgt** [j2969719/doublecmd-plugins#25]
OOXML and ODF files have written app and version name of last save. 
It is inside .zip file for example in \docProps\app.xml for DOCX ( <Application> and <AppVersion> ) and meta.xml for ODF ( <meta:generator> ).
I hope this is a good place to ask for a script that would read those names and versions from office files (so that we don't have to unzip and click and open each time).
Thanks for considering.

**Comment by j2969719** [comment]
also added `Application` field to the exiftoolwdx.lua

**Comment by gitgt** [comment]
I didn't know, thanks. 
I put OpenOfficeInfo and Office Open XML in \plugins\wdx\ and added in \Options\Plugins but what then? How to use it? Not obvious, I couldn't find. 
Another problem is that Office Open XML doesn't have 64-bit version.
I also added exiftoolwdx.lua and assigned a toolbar icon to it but also nothing, how does that work?
Please put some explanation on the main page.

**Comment by j2969719** [comment]
https://doublecmd.h1n.ru/viewtopic.php?p=36165#p36165

**Comment by gitgt** [comment]
Now that I see how it works, search of files for some string is not what I wanted. 
But with this I got what I Needed: I made Custom Columns with these plugins (I also switched to 32-bit to be able to use both). Thanks!

As for usage, please continue in forum.

**Comment by Skif-off** [comment]
@gitgt 

>  Another problem is that Office Open XML doesn't have 64-bit version.

https://totalcmd.net/plugring/office2007wdx_64.html
