### ISSUE TITLE
qt5 error when using wlxwebkit_qt5

### ISSUE THREAD

**Issue by crotoc** [j2969719/doublecmd-plugins#26]
I am trying to preview html using plugin of wlxwebkit_qt5. My system is wslg ubuntu 2204 lts, and I have installed required libraries (libqt5webkit5) and the plugin can be added. When pressing ctrl+Q to preview a html file, it throws an error: 

_QWidget: Must construct a QApplication before a QWidget_

Can some help me fix the question? I am not familiar with c++ and qt5 so cannot debug it by myself.

I am using DC to view some htmls on a remote server and prevent from downloading them to local computer. 

Thanks!

**Comment by j2969719** [comment]
please provide more information about Double Commander (F1 > Copy to clipboard)

**Comment by crotoc** [comment]
![image](https://user-images.githubusercontent.com/12446554/171733858-b93fc2fb-d3dd-4e28-b3fc-b67f668004c6.png)

**Comment by j2969719** [comment]
this is a plugin for doublecmd-qt not gtk

**Comment by j2969719** [comment]
yes

**Comment by crotoc** [comment]
wlxwebkit is a plugin that I have successfully installed and previewed some htmls. The only problem is the wlxwebkit cannot zoom in and out the page so that I can screenshot some results. Do you have recommendations of that? A plugin that can view html and zoom in/out when needed. Thanks!

**Comment by j2969719** [comment]
this is simply not implemented
only basic webpage view is implemented here, nothing more

**Comment by crotoc** [comment]
I tried qt5 version and there is no problem for viewing html. No zoom in/out as well. Hope you can help implement it in sometime the future. I will be trying to implement it if I am able to figure out how to do it. Thanks very much!

**Comment by j2969719** [comment]
btw [webengine_qt5](https://github.com/j2969719/doublecmd-plugins/tree/master/plugins/wlx/webengine_qt5) also doesnt support ctrl + mouse wheel zoom out of the box?

**Comment by crotoc** [comment]
The webendine_qt5 can be added but fails to work. The error msg is :

_Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed._

An empty page is shown after waiting for about a miniute.

**Comment by j2969719** [comment]
added hotkeys for zoom (`Ctrl+Plus`, `Ctrl+Minus`, `Ctrl+0`)
...but since they dont work in `Ctrl+Q` also added an additional panel with buttons (it can be disabled in the `$DC_CONFIG_PATH/j2969719.ini` config).

**Comment by crotoc** [comment]
Bro, thanks so much! I just read some documents about qt5 and you have done it. Appreciate a ton!
