### ISSUE TITLE
gtksourceview: depends libconfig.so

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#3]
Бинарник отсюда требует ```libconfig.so.11```, а у меня ```libconfig.so.9``` (линк на ```libconfig.so.9.2.0```), при этом линка ```libconfig.so```, как у некоторых, нет и, видимо, с другими версиями ОСи и либ всплывёт тоже.
Это как-то можно разрулить не пересобирая бинарник под себя?

**Comment by j2969719** [comment]
хз, не пересобирая это LD_LIBRARY_PATH походу
у портативок в скрипте doublecmd.sh например так:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)`

вообще бинарники надо убирать(особенно учитывая что по отдельности собирается *.wlx, а dc на автомате подхватывает *.wlx64 если есть). они тут только для меня лежат т.к. мне оно так просто быстрее между компами их перебрасывать, чем с релизами

**Comment by Skif-off** [comment]
> вообще бинарники надо убирать

Ну, тут как сказать, кому-то проще забрать готовое. С другой стороны, тогда надо допиливать readme (версии, чё-куда)...

**Comment by j2969719** [comment]
арчебинарники убрал в https://github.com/j2969719/doublecmd-plugins/releases 
но лучше собирать со своими либами
readme для этого говна писать как-то совсем лениво

**Comment by alexx2000** [comment]
ИМХО для конфига лучше использовать [GKeyFile](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html), нативная штука для GTK.

**Comment by j2969719** [comment]
ок, заменил на него
