### ISSUE TITLE
Кнопка для патчей с git

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#4]
Предлагаю добавить в [buttons.md](https://github.com/j2969719/doublecmd-plugins/blob/master/buttons.md) пример кнопки создания патча для изменённого файла в локальном git-репозитории (не проиндексированные изменения, т.е. до ```git add``` или сразу ```git commit```!)
```xml
DOUBLECMD#TOOLBAR#XMLDATA<?xml version="1.0" encoding="UTF-8"?>
<doublecmd>
  <Program>
    <ID>{7E175254-7084-4705-BD26-BABB6E1B9329}</ID>
    <Icon>cm_comparecontents</Icon>
    <Hint>git: view diff (current file, active panel)</Hint>
    <Command>git</Command>
    <Params>%t1 diff %fs &gt; patch.diff</Params>
  </Program>
</doublecmd>
```

**Comment by j2969719** [comment]
ок, добавил, но толком не проверял

**Comment by Skif-off** [comment]
[Пример работы кнопки.](https://github.com/doublecmd/plugins/issues/5)

**Comment by j2969719** [comment]
не, я в смысле всю менюху на гит не проверял, которую вместе с кнопкой тогда добавил
