### ISSUE TITLE
wlxPView (aka dcpoppler): Плагин сохраняет положение прокрутки при пролистывании страниц файла

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#6]
Крайне неудобно. Это связано с плагином или DC (у DC была [проблема при переходе к следующему/предыдущему файлу](https://doublecmd.sourceforge.io/mantisbt/view.php?id=1933), а тут - страницы одного)?

**Comment by j2969719** [comment]
не, он просто так перерисовывает холст по нажатию. я вряд ли это говно ковырять буду т.к. есть и evince и atril и zathura которые могут не только в pdf. у убунт конечно скорей всего нет готовых пакетов с gtk2 evince или  atril, но вот zathura должна быть. она цепляется сокетом как gvim так что должна пойти

**Comment by j2969719** [comment]
накастылял корявый сброс

**Comment by Skif-off** [comment]
Спасибо, вроде работает. 

Хотелось зависимостей по минимуму :) ```evince``` в комплекте только 3.0, ```atril``` не устраивает зависимостями. Пробую ```zathura``` поинтереснее тем, что можно менять масштаб.
