### ISSUE TITLE
mpv (wlx): Add FLAC to default detect string

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#7]
It's a fairly popular format.

Big thanks, good plugin :)

**Comment by j2969719** [comment]
будь предупрежден, плагин сразу в ctrl+q окно не схватывает нужно туда-сюда по файлам пройтись
расширение потом добавлю

**Comment by Skif-off** [comment]
Не успел заметить, забавно, а почему? :)

Кстати, спасибо за ```--force-window=yes```, у меня mpv на кнопке голый, лишь с ```%p```, висел, решил проверить, как он с музыкой дружит: в итоге слышу четыре трека одновременно и никаких окон :))) Минуту тупил, прежде чем полез в диспетчер задач.

**Comment by j2969719** [comment]
этот костыль по сути просто передает место для отрисовки гуя при запуске, без принудительного оконного mvp ему просто не за что зацепится
в чем прикол с быстрым просмотром нужно спрашивать уже у человека хоть немного понимающего в апи и кодинг - я как бэ дно. хз, видать с точки зрения гтк есть какая-то разница между загрузкой первого файла в быстром просмотре и загрузкой там следующего. похожий косяк но уже наоборот есть у говнокостыля на abiword - там от загрузки следующего файла с ctrl+q вылазит вылет с unsupported encoding. а вот при встраивании сокетом(zathura/gvim) таких проблем вроде нет, хз..
