### ISSUE TITLE
mimescript (wlx): Can not build on *buntu 

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#8]
Can you try to check? ```mimescript.wlx``` from [here](https://github.com/j2969719/doublecmd-plugins/releases) works fine.

P.S. I use Xubuntu 17.10 x64.

**Comment by j2969719** [comment]
только если после нг. может выхлоп остался? simplefileinfo собирается? там тоже libmagic 
или может просто опять `-Wl,--no-as-needed` в мейкфайле не хватает

**Comment by Skif-off** [comment]
> simplefileinfo собирается?

Да, без проблем собирался и собирается.

> может выхлоп остался?

Не, не остался. Сейчас проверил ```mimescript``` - отлично собирается, полагаю, пофикшено, спасибо.

**Comment by j2969719** [comment]
закрываю. напишешь если что
