### ISSUE TITLE
zathura (wlx): Игнорирование истории

### ISSUE THREAD

**Issue by Skif-off** [j2969719/doublecmd-plugins#9]
Возможно, есть смысл добавить параметр ```--page=1```: сохраняет кучу всего и, блин, номер страницы :))) Натурально заколебало :)

Историю ввода (разные внутренние команды) и закладки можно выпилить, добавив в ```~/.config/zathura/zathurarc``` строку ```set database null``` (ну и буфер обмена поприятнее с ```set selection-clipboard clipboard``` там же), а вот с историей - болт. Если только лезть в исходники zathura, ну или пробовать мудрить с ```--config-dir=path``` и ```--data-dir=path``` и ставить запрет на запись в файл ```~/.local/share/zathura/history```.

**Comment by j2969719** [comment]
я проброс primary>clipboard по ctrl+с в принципе добавил так что поведение выделил>ctrl+c более-менее нормальное должно быть. по переносу конфига в папку с костылем - хз, оно возможно но нужно опять цеплять `dlfcn`. короче может пощупаешь параметры еще и скажешь которые лучше тебе пойдут для дефолта, а я потом их добавлю т.к. поведение у нее таки да немного "своеобразное" ака вимовское, да и сам я пользую сейчас atrli

**Comment by j2969719** [comment]
всобачил конфиг для доп. параметров и записи настроек zathura в папку с костылем. но толком это дело не проверял, так что будь готов ко всему

**Comment by Skif-off** [comment]
Спасибо, вроде работает, по дефолту ```Params=--page=1``` можно оставить, думаю (иначе будет постоянно открывать в сохранённом месте).

С конфигом вроде работает и, похоже, ```set database null``` в конфиге запрещает сохранять вообще всю историю (хотя гугление выдало, что только закладки и историю ввода команд), у себя сделал так
```ini
[Settings]
# Additional command-line parameters
#Params=--page=1
# Store data in the plugin directory
ExternalCfg=true
```
и положил рядом ```zathurarc``` cо строкой ```set database null```, пока вроде порядок. Радует, что заметно пошустрее wlxPView (aka dcpoppler).

**Comment by j2969719** [comment]
ну тогда наверное оставлю как есть. `zathurarc` класть наверное не буду - вдруг поведение у старых/новых версий на `set database null` другое. закрываю
